export const CREATE_BOARD = "CREATE_BOARD";
export const SET_CREATED_BOARD = "SET_CREATED_BOARD";
export const GET_ALL_BOARDS = "GET_ALL_BOARDS";
export const SET_ALL_BOARDS = "SET_ALL_BOARDS";

export const GET_BOARD = "GET_BOARD";
export const SET_BOARD = "SET_BOARD";

export const CREATE_LIST = "CREATE_LIST";
export const SET_LIST = "SET_LIST";

export const CREATE_CARD = "CREATE_CARD";
export const SET_CARD = "SET_CARD";

export const UPDATE_LIST_POSITION = "UPDATE_LIST_POSITION";
export const UPDATE_CARD_POSITION = "UPDATE_CARD_POSITION";

export const UPDATE_LIST_TITLE = "UPDATE_LIST_TITLE"